language: node_js
node_js: 4.1.1
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm set registry https://registry.npmjs.org/
- gulp build
- node_modules/protractor/bin/webdriver-manager update
script: gulp test
after_success:
- cat coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  email: false
addons:
  sauce_connect: true
  hosts:
    myself