language: node_js
node_js: '0.12.7'
script: gulp test
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - node_modules/bower/bin/bower install
    - gulp build
    - webdriver-manager update
    - webdriver-manager start
notifications:
  email: false