language: node_js
node_js:
    - '0.12'
script: gulp test --single-run
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - node_modules/bower/bin/bower install
    - gulp build
notifications:
  email: false